### ISSUE TITLE
Spectrum Display Improvement

### ISSUE THREAD

**Issue by Colerar** [TypesettingTools/Aegisub#149]
1. Different Spectrum Mapping, likes in Adobe Audition, from linear to logarithmic.
   > In fact, there is a PR #94, and it works well for me. Maybe this branch is no longer active :( so not merged
2. Better Window Function - [Wikipedia](https://en.wikipedia.org/wiki/Window_function)
   Based on #94, there are still some issues.
   <img width="50%" alt="image" src="https://user-images.githubusercontent.com/62297254/156371213-caaa5b26-71a8-488c-9fbd-db52dda26919.png">
   Look at the underlined part, it seems strange. As far as I know, the performance above is similar to `Hamming` window funtion, screenshot in Adobe Audition - `Hamming` window function:
   <img width="50%" alt="Screenshot in Adobe Audition - Hamming Window Function" src="https://user-images.githubusercontent.com/62297254/156372443-6767ac63-75aa-457b-88f8-75c1091a98aa.png">
   FFmpeg provides varieties of window functions, see [FFmpeg filters - showfreqs](https://ffmpeg.org/ffmpeg-filters.html#showfreqs). For reference, Adobe Audition uses Blackman-Harris (i.e. `bharris`) as the default.

:) The two enhancement requests are in order to improve efficiency. I lack cpp development experience so I can only raise a issue instead of PR. 😢

**Comment by EleonoreMizo** [comment]
2. Currently, there is no specific windowing (aka rectangular window) in Aegisub. In `AudioSpectrumRenderer::FillBlock()`, it should have been located between `ConvertToFloat()` and `fftw_execute()`. Given the goal of this spectrogram I’m not sure this is really required, but I could add one. However I’m not sure that what we see in the first screenshot is the result of a lack of window—maybe.

**Comment by Colerar** [comment]
If you can add one, I'll appreciate so much. :)

**Comment by EleonoreMizo** [comment]
I implemented a Blackman-Harris window, but I won’t make a pull request for it because this is a clear regression from a productivity point of view. The reason is simple: with a rectangular window, the main lobe of a frequency component is very sharp (and the side lobes quite high but this is not a problem here), whereas the main lobe of a more sophisticated window is much wider, and it looks blurry when displayed. So voiced component are less obvious to detect visually.

![aegisub-win-rectangular](https://user-images.githubusercontent.com/9513144/163675614-56c32ab6-baf0-4106-a487-b659626ceb31.png) ![aegisub-win-blackman-harris](https://user-images.githubusercontent.com/9513144/163675620-358fdb8e-4a23-4cfa-bd20-5e9207abee0a.png)
Rectangular (no window) | Blackman-Harris

**Comment by Colerar** [comment]
Thanks for your contribution again.

I partly agree with you. Blackman-Harris windows looks a bit blurry. But it improves the SNR. If a source audio has a lot of noise, Blackman-Harris may be a better choice. 

You can add an option if you want, let user to decide. Options are better than nothing.

**Comment by Colerar** [comment]
For example, in this case, low frequency and repetitive SFX (can be regraded as noise) make the spectrum out of reference value.

Rectangular window:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/62297254/163801407-18a1b8cc-f75a-42be-8b13-1c52ac3a18ba.png">

Blackman-Harris:

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/62297254/163802008-d29f91bf-f9bb-4ce5-bb62-201fb044d8be.png">
