### ISSUE TITLE
List of dependencies for build on Linux

### ISSUE THREAD

**Issue by Naadiyaar** [TypesettingTools/Aegisub#170]
I want to build the binary on X64-86, but couldn't find which dependencies are required.
I can see the _Prerequisites_ section at README file, but a few options are Windows specific, so that would be great if you provide me a list of dependencies for build and install on an RPM based machine.

**Comment by Totto16** [comment]
Look into the https://github.com/TypesettingTools/Aegisub/blob/master/.github/workflows/ci.yml file, there is a complete list for debian / ubuntu based systems, if some of that packages aren't available in rpm based machines just replace them with their counterparts in rpm:
 debian list: `sudo apt-get install ninja-build build-essential libx11-dev libwxgtk3.0-gtk3-dev libfreetype6-dev pkg-config libfontconfig1-dev libass-dev libasound2-dev libffms2-dev intltool libboost-all-dev`

**Comment by Naadiyaar** [comment]
Thanks for response!

These are RPM equipments of packages AFAIK
.deb -> .rpm

```
build-essentiali -> make automake gcc gcc-c++ kernel-devel
libx11-dev -> libX11-devel
libwxgtk3.0-gtk3-dev -> https://stackoverflow.com/questions/73776717/deb-packages-rpm-counterpart
libfreetype6-dev -> freetype-devel
libfontconfig1-dev -> fontconfig-devel
libass-dev -> libass-devel
libasound2-dev -> alsa-lib-devel
libffms2-dev -> https://stackoverflow.com/questions/73776717/deb-packages-rpm-counterpart
libboost-all-dev -> boost-devel
```

**Comment by Totto16** [comment]
some packages like ffms2 are not required, only recommended, since when their absent their going to be built locally, which increases build time. These packages are the ones that have a .wrap file in https://github.com/TypesettingTools/Aegisub/tree/master/subprojects

For the future of aegisub I at least plan to make a flatpak app, so that something like different required packages for different platforms (deb, rpm, dnf etc.) are irrelevant, but I also only needed it to build for my system (ubuntu) so I didn't do that yet. If you need some additional help regarding linux compiling feel free to ask. It should build with these rpm packages, but don't use meson 0.63.0 or above, the oldest supported meson version is 0.62.2, due to some cmake sandboxing issues in 0.63.0 and above :)

**Comment by eli-schwartz** [comment]
> but don't use meson 0.63.0 or above, the oldest supported meson version is 0.62.2, due to some cmake sandboxing issues in 0.63.0 and above :)

For the record, this is false -- there was a cmake subprojects regression in 0.63.0, but not "above", and it was fixed in the .1 release last month. You can safely use the latest version of any major.minor branch.

**Comment by Totto16** [comment]
as far as I tested 0.63.1 solves one issue, but not all, I at least couldn't compile it with meson 0.63.1, but maybe due some subprojects that i compile

**Comment by Naadiyaar** [comment]
> For the future of aegisub I at least plan to make a flatpak app

That would be awesome and save lots of users from unnecessary headaches.

>If you need some additional help regarding linux compiling feel free to ask.

Thank you so much, if there was a problem, I will open a new issue.

**Comment by Naadiyaar** [comment]
Since the main question has been answered, I think it is the right thing to close the issue

**Comment by eli-schwartz** [comment]
> as far as I tested 0.63.1 solves one issue, but not all

Whatever other issues you had were presumably not "cmake subproject" issues.

**Comment by Totto16** [comment]
> > For the future of aegisub I at least plan to make a flatpak app
> 
> That would be awesome and save lots of users from unnecessary headaches.
> 
> > If you need some additional help regarding linux compiling feel free to ask.
> 
> Thank you so much, if there was a problem, I will open a new issue.

I finally made a flatpak build, If you're still interested, it has some newer dependencies and some fixes for that, so It wont likely be merged into this repo soon, but you can look here: https://github.com/Totto16/Aegisub/tree/master
( I made it some weeks ago, but today this conversation cam eto mind)

And get bundle e.g from [here](https://github.com/Totto16/Aegisub/actions/runs/6792265394) (or build it yourself, see [compile.sh](https://github.com/Totto16/Aegisub/blob/master/compile.sh) )
NOTE: that it still has an annoying boost locales issues, that I have sorted out on 1/2 of my machines and someday I will fix that  (nothing that stops it from running, it says std::bad_cast, you will likely see xD), that I have to sort out, but otherwise it runs flawlessly and since it's flatpak I can conform that for any machine 😄
