### ISSUE TITLE
Will there be a new release?

### ISSUE THREAD

**Issue by AuroraMartell** [TypesettingTools/Aegisub#181]
There hasn't been a new release for this very useful software in nine years. And TBH, the program needs a few things, in my opinion.

- [ ] A newer, cleaner interface.
- [ ] A better toolbar
- [ ] The option to burn in subtitles

**Comment by arch1t3cht** [comment]
Do you offer to work on these things?

**Comment by mihawk90** [comment]
> * The option to burn in subtitles

Seriously who still burns in subtitles? Every halfway decent media player under the sun supports soft subs these days. We're not in the 1980s anymore, it's time to move on.

---

Regardless, even without the *"needed"* things, the question is somewhat valid I'd say. Development is still active after all and if I'm interpreting what GitHub is displaying correctly, there's been roughly 700 commits since the last release: [v3.2.2](https://github.com/Aegisub/Aegisub/releases/tag/v3.2.2) shows "[407 commits to master since this release](https://github.com/Aegisub/Aegisub/compare/v3.2.2...master)", and its master is "[281 commits behind](https://github.com/Aegisub/Aegisub/compare/master...TypesettingTools:Aegisub:master) TypesettingTools:master.".

Would be nice to see the results of the work being done 😄

**Comment by AuroraMartell** [comment]
> Seriously who still burns in subtitles? Every halfway decent media player under the sun supports soft subs these days. We're not in the 1980s anymore, it's time to move on.

I like having burned-in subs because most of the videos I work on are meant to be watched on TVs (usually through flash drives). It's a personal preference, man.

**Comment by witchymary** [comment]
This can easily done with scripts like Encode Clip from Dependency Control. I don't think it's something that should be built-in into Aegisub; it's the job of encoding and video editing tooling at the end of the day. It'd be overstepping the responsibilities of subtitle editing software.

**Comment by AuroraMartell** [comment]
> Do you offer to work on these things?

I can't code but I can give ideas.
