### ISSUE TITLE
[BUG] Duplicate right menu options

### ISSUE THREAD

**Issue by obsession9** [TypesettingTools/Aegisub#249]
When I upgraded from 3.2.2 to 3.4.0, two duplicate right-click menu options appeared.
![image](https://github.com/user-attachments/assets/4ac09750-782f-4cd6-95a7-6b6d1ef9e5df)

For the first option, the corresponding subtitle file is not opened after the program is started.

For the second option, an error is reported.
![image](https://github.com/user-attachments/assets/c7d5862e-a758-4ed5-97c8-ca8aa8a62349)
It show that: can't find ffms2_64.dll.

How can I delete the invalid item?

**Comment by witchymary** [comment]
I'd assume the other entry if from an older version of Aegisub that's somehow still lingering around.

**Comment by arch1t3cht** [comment]
That's what I'd guess too. Do you have an `aegisub64.exe` file in your Aegisub install folder? If so you can delete that. Or, if you want to completely remove all of the associations, you can try installing whatever Aegisub version you used before 3.4.0 again, then uninstalling using the actual uninstaller, and then reinstalling 3.4.0.

The subtitle file not actually being opened is probably because of #219 , which will be fixed in 3.4.1.

**Comment by obsession9** [comment]
Yes, this can be fixed by uninstalling
