### ISSUE TITLE
meson build system

### ISSUE THREAD

**Issue by FichteFoll** [TypesettingTools/Aegisub#26]
A while ago, @lachs0r ported the current autotools build system to use meson and I adapted that to work on my machine as well. The current progress is available at https://github.com/lachs0r/Aegisub/tree/meson/ (+2 unmerged PRs). I do not know if this works at the moment since I stopped using my meson fork when I noticed frequent crashes with automation that didn't occur on `origin/master`.

Ideally, this should ease the build process for Windows a lot and might even enable cross-compilation, though last I remember that was stuck on a bug in boost. I am most certainly *not* an expert in this area.

Just putting this up here so it isn't forgotten. And to gather interest.

**Comment by CoffeeFlux** [comment]
Yeah, I've got this on the projects board but it should probably be an issue on here. I'll move the other stuff to actual issues once I get the release out (aka once the ffms2 issue is fixed).

As far as this particular issue goes, I did some work on making luajit work on Windows that I need to go back and clean up since I didn't really know what I was doing, and then some other random meson-related work that's I think in a similar situation.

**Comment by CoffeeFlux** [comment]
Did some more work on this, but I don't think it's viable to be building on Windows until this module gets merged in: https://github.com/mesonbuild/meson/issues/4316

**Comment by CoffeeFlux** [comment]
Libass is ported to meson, which makes this much easier. Hopefully this weekend?

**Comment by CoffeeFlux** [comment]
Running into this when trying to link libass statically: https://github.com/fribidi/fribidi/issues/100

I can't release a build until that's fixed, but I should be able to keep working on Aegisub at least since it seems fine if I link dynamically.

**Comment by CoffeeFlux** [comment]
Libass port updated, and now works correctly with the text exe as well as when included in another project (SubInspector). https://github.com/TypesettingTools/libass/tree/meson

**Comment by CoffeeFlux** [comment]
In theory, things should now be functional on OSX and Linux. Windows... is getting there.
