### ISSUE TITLE
AssDraw

### ISSUE THREAD

**Issue by dvdmasters** [TypesettingTools/Aegisub#54]
Is it possible to reinsert AssDraw3 link directly in aegisub toolbar?

**Comment by CoffeeFlux** [comment]
AssDraw was removed because it's bad, broken, and I'm not interested in supporting it. The recommended workflow for complex vector drawings is to use either Adobe Illustrator or something like CorelDraw, as both have a conversion script back to Aegisub paths. AI in particular is well supported via [AI2ASS](https://github.com/TypesettingTools/AI2ASS), and additional tooling is in progress to make it easier to use (see [aegisync-video-preview](https://github.com/TypesettingTools/aegisync-video-preview)).

**Comment by dvdmasters** [comment]
thanks for your answer

**Comment by CoffeeFlux** [comment]
I forgot to mention that there's a script to convert clips to drawings that works well for a lot of stuff since there are other clip manipulation scripts. Anything super fancy will require an external program, but that may serve a lot of your needs.
