### ISSUE TITLE
Sound mismatch

### ISSUE THREAD

**Issue by fomat** [TypesettingTools/Aegisub#68]
Voices did not match with the video. I changed all the timings, and then... discovered, that the mismatch was only in this aegisub version.

**Comment by NoNameUserDev** [comment]
Hi! I have had same problem )
Is the voice a bit noisy or dot-dot and timing is missed? If so, just replace *.exe to this from [link](https://drive.google.com/open?id=1BAQHKvIqgWQZvzEZvs4FOip95B-AUabO)
There are 8992 build and there this problem is fixed.
But still many problems remain :(
Problems associated with the applying karaoke effects and suddenly getting error... I hope that they'll fix this in the future.

**Comment by fomat** [comment]
Oh, god, thank you SO MUCH. It works!

**Comment by NoNameUserDev** [comment]
@fomat Hi! Glad to see it works ) You need to close the issue since the problem is resolved ^_^
